class DataBun:
    BLACK_BUN = 'black bun'
    WHITE_BUN = 'white bun'
    RED_BUN = 'red bun'
    BLACK_BUN_PRICE = 100
    WHITE_BUN_PRICE = 200
    RED_BUN_PRICE = 300

class DataIngredient:
    INGREDIENT_TYPE_SAUCE = 'SAUCE'
    INGREDIENT_TYPE_FILLING = 'FILLING'

    INGREDIENT_NAME_HOT_SAUCE = 'hot sauce'
    INGREDIENT_NAME_SOUR_CREAM = 'sour cream'
    INGREDIENT_NAME_CHILI_SAUCE = 'chili sauce'
    INGREDIENT_NAME_CHILI_CUTLET = 'cutlet'
    INGREDIENT_NAME_CHILI_DINOSAUR = 'dinosaur'
    INGREDIENT_NAME_CHILI_SAUSAGE = 'sausage'

    INGREDIENT_PRICE_HOT_SAUCE = 100
    INGREDIENT_PRICE_SOUR_CREAM = 200
    INGREDIENT_PRICE_CHILI_SAUCE = 300
    INGREDIENT_PRICE_CHILI_CUTLET = 100
    INGREDIENT_PRICE_CHILI_DINOSAUR = 200
    INGREDIENT_PRICE_CHILI_SAUSAGE = 300
